# This is a TOML document config

title = "droid configuration file"

[base]

raw_rules_directory = "rules/raw"

sigma_validation_config = "validation/validate.yml"

[platforms.splunk]

[platforms.splunk.pipelines.windows_process_access]

pipelines = ["splunk_windows", "splunk_cim"]
product = "windows"
category = "process_access"